---

- name: Airflow | Ensure airflow directories structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
  with_items:
    - "{{ airflow_logs_folder }}"
    - "{{ airflow_child_process_log_folder }}"
    - "{{ airflow_dags_folder }}"
    - "{{ airflow_plugins_folder }}"

- name: Airflow | Copy gunicorn logrotate config
  template:
    src: gunicorn-logrotate.j2
    dest: /etc/logrotate.d/airflow
    mode: 0644
    owner: root
    group: root

- name: Airflow | Copy basic airflow config file (< 2.0)
  template:
    src: "{{ airflow_config_template_path }}"
    dest: "{{ airflow_conf_path }}/airflow.cfg"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  register: airflow_config
  when: airflow_version is version( '2.0.0', '<')
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Copy basic airflow config file (>= 2.0)
  template:
    src: "{{ airflow_config_template_path_v2 }}"
    dest: "{{ airflow_conf_path }}/airflow.cfg"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  register: airflow_config
  when: airflow_version is version( '2.0.0', '>=')
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Initializing DB < 2.0
  command: "{{ airflow_executable }} initdb"
  become: true
  become_user: "{{ airflow_user }}"
  tags:
    skip_ansible_lint
  when:
    - airflow_version is version( '2.0.0', '<')
    - (airflow_install.changed or airflow_config.changed)
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Initializing DB > 2.0
  command: "{{ airflow_executable }} db init"
  become: true
  become_user: "{{ airflow_user }}"
  when:
    - airflow_version is version( '2.0.0', '>=')
    - airflow_install.changed or airflow_config.changed
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Check Admin user (> 2.0)
  command: "{{ airflow_executable }} users list"
  register: airflow_check_admin
  changed_when: false
  when: airflow_version is version( '2.0.0', '>=')
  no_log: true

- name: Airflow | Create Admin user (> 2.0)
  command:
    argv:
      - "{{ airflow_executable }}"
      - users
      - create
      - --username
      - "{{ airflow_admin_user.username }}"
      - --password
      - "{{ airflow_admin_user.password }}"
      - --firstname
      - "{{ airflow_admin_user.firstname }}"
      - --lastname
      - "{{ airflow_admin_user.lastname }}"
      - --role
      - "{{ airflow_admin_user.role }}"
      - --email
      - "{{ airflow_admin_user.email }}"
  no_log: true
  when:
    - airflow_version is version( '2.0.0', '>=')
    - "airflow_admin_user.email not in airflow_check_admin.stdout"

- name: Airflow | Copy extra airflow config files (provided by playbooks)
  copy:
    src: "{{ item }}"
    dest: "{{ airflow_conf_path }}/{{ item | basename }}"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  with_fileglob:
    - "{{ airflow_extra_conf_path }}/*"
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Copy extra airflow config templates (provided by playbooks)
  template:
    src: "{{ item }}"
    dest: "{{ airflow_conf_path }}/{{ item | basename }}"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  with_fileglob:
    - "{{ airflow_extra_conf_template_path }}/*"
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Add variables from configuration file
  command: "{{ airflow_executable }} variables -s {{ item.key }} {{ item.value }}"
  become: true
  become_user: "{{ airflow_user }}"
  with_items: "{{ airflow_admin_variables }}"
  tags:
    skip_ansible_lint

- name: Airflow | Add connections from configuration file
  command: "{{ airflow_executable }} connections -a \
  {% for key, value in item.iteritems() %}--{{ key }} '{{ value }}' \
  {% endfor %}"
  become: true
  become_user: "{{ airflow_user }}"
  with_items: "{{ airflow_admin_connections }}"
  tags:
    skip_ansible_lint
