---
# handlers file for airflow-role

- name: Restart airflow-webserver
  ansible.builtin.systemd:
    name: airflow-webserver
    state: restarted
  when: >-
   airflow_services['airflow_webserver']
   and airflow_services['airflow_webserver']['enabled']

- name: Restart airflow-scheduler
  ansible.builtin.systemd:
    name: airflow-scheduler
    state: restarted
  when: >-
   airflow_services['airflow_scheduler']
   and airflow_services['airflow_scheduler']['enabled']

- name: Restart airflow-worker
  ansible.builtin.systemd:
    name: airflow-worker
    state: restarted
  when: >-
   airflow_services['airflow_worker']
   and airflow_services['airflow_worker']['enabled']

- name: Restart airflow-flower
  ansible.builtin.systemd:
    name: airflow-flower
    state: restarted
  when: >-
   airflow_services['airflow_flower']
   and airflow_services['airflow_flower']['enabled']
