# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v dnf) ]; then dnf update -y && dnf install -y python3 sudo bash ca-certificates systemd systemd-sysv; fi
