---
dependency:
  name: galaxy

driver:
  name: podman

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: airflow-debian
    groups:
      - airflow_group
    image: ${MOLECULE_DISTRO:-debian:bookworm-slim}
    dockerfile: Dockerfile-bookworm.j2
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    exposed_ports:
      - 8088/tcp
      - 8080/tcp
      - 8081/tcp
      - 5000/tcp
      - 5555/tcp
    published_ports:
      - 0.0.0.0:8088:8088/tcp
      - 0.0.0.0:8080:8080/tcp
      - 0.0.0.0:8081:8081/tcp
      - 0.0.0.0:5000:5000/tcp
      - 0.0.0.0:5555:5555/tcp

  - name: airflow-ubuntu
    groups:
      - airflow_group
    image: ${MOLECULE_DISTRO:-ubuntu:jammy}
    dockerfile: Dockerfile-jammy.j2
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    exposed_ports:
      - 8089/tcp
      - 8082/tcp
      - 8083/tcp
      - 5001/tcp
      - 5556/tcp
    published_ports:
      - 0.0.0.0:8089:8088/tcp
      - 0.0.0.0:8082:8080/tcp
      - 0.0.0.0:8083:8081/tcp
      - 0.0.0.0:5001:5000/tcp
      - 0.0.0.0:5556:5555/tcp

  - name: airflow-redhat
    groups:
      - airflow_group
    image: ${MOLECULE_DISTRO:-rockylinux:8}
    dockerfile: Dockerfile-rocky.j2
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
#    command: '/lib/systemd/systemd'
    command: '/sbin/init'
    stop_signal: 'RTMIN+3'
    exposed_ports:
      - 8090/tcp
      - 8084/tcp
      - 8085/tcp
      - 5002/tcp
      - 5557/tcp
    published_ports:
      - 0.0.0.0:8090:8088/tcp
      - 0.0.0.0:8084:8080/tcp
      - 0.0.0.0:8085:8081/tcp
      - 0.0.0.0:5002:5000/tcp
      - 0.0.0.0:5557:5555/tcp

provisioner:
  name: ansible
  inventory:
    host_vars:
      airflow-redhat:
        airflow_python_version: "3.11"
      airflow-ubuntu:
        airflow_python_version: "3.10"

scenario:
  name: default

verifier:
  name: ansible

