---

- name: Converge
  hosts: airflow_group
  roles:
    - role: airflow-role
  environment:
    AIRFLOW_HOME: "{{ airflow_app_home }}"
    AIRFLOW_CONFIG: "{{ airflow_conf_path }}/airflow.cfg"
  vars_files:
    - ../../defaults/main.yml
    - ./group_vars/airflow/main.yml
